version: "3.9"

services:
  like:
    image: like:latest
    build:
      context: ${PWD}/like
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running Like Backend' && ./like"
    env_file:
      - ${PWD}/.env
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - ${LIKE_PORT}:${LIKE_PORT}
    networks:
      - like_network
    restart: unless-stopped
