version: "3.9"

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --port ${REDIS_PORT} --save 20 1 --loglevel warning
    env_file:
      - ${PWD}/.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - like_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: on-failure

volumes:
  redis_data:
